### ISSUE TITLE
unifi.boostchicken.io down

### ISSUE THREAD

**Issue by dubhunter** [unifi-utilities/unifios-utilities#522]
Looks like unifi.boostchicken.io is down. I'm sure you've been getting lots of traffic lately, but it would be awesome to get an update or the files hosted somewhere else. (Trying to get podman on a UDMP 2.4.27).

Thanks for all you do!

<img width="1097" alt="Screenshot 2023-03-21 at 8 55 00 AM" src="https://user-images.githubusercontent.com/556503/226666403-d49558d6-fc13-4127-98ff-58bc2a7ad22a.png">

**Comment by Eric-Vignola** [comment]
confirmed, just as I was trying to manually install podman

**Comment by boostchicken** [comment]
I just tried it and it works?

https://unifi.boostchicken.io/

**Comment by mabunixda** [comment]
Works also for me, but reponse time is quite high ....

[is it down right now](https://www.isitdownrightnow.com/unifi.boostchicken.io.html) reports it as down at the moment...

**Comment by TheBlindHacker** [comment]
Just tried, can confirm it is down, at this moment.

**Comment by boostchicken** [comment]
Yeah I am movving my network to 25Gbe, there are some hicups.

I havve no clue why the response is high.  This is I have 2 1gig synchronus fiber lines load balanced.

Also the server with IPFS is a 28 corem 512GB of ram, 50Gbe to the network. I think IPFS just sucks at this point. Port 4001 for TCP and UDP are forwarded which is what is needed.  I also directly peer with cloudflare.  Anyone have any other thoughts?

**Comment by lucasreiners** [comment]
I also have trouble downloading podman from https://unifi.boostchicken.io/udmpro-podman-install.zip

```
ipfs resolve -r /ipns/unifi.boostchicken.io/udmpro-podman-install.zip: no link named "udmpro-podman-install.zip" under QmXuHrSrLntBfKmcwAPHq2S3BeHdEviHMzvvZh4Q87ay3E
```

**Comment by ddkedr** [comment]
> I also have trouble downloading podman from https://unifi.boostchicken.io/udmpro-podman-install.zip
> 
> ```
> ipfs resolve -r /ipns/unifi.boostchicken.io/udmpro-podman-install.zip: no link named "udmpro-podman-install.zip" under QmXuHrSrLntBfKmcwAPHq2S3BeHdEviHMzvvZh4Q87ay3E
> ```

I think this also breaks [00-podman.sh](https://github.com/unifi-utilities/unifios-utilities/blob/main/podman-install/on_boot.d/00-podman.sh) script which has `DESIRED_ZIPFILE="$(udm_model)-podman-install.zip"`. I've modified this variable to `DESIRED_ZIPFILE="podman-udmse-udmpro-v2023-03-23-4778.zip"` but there are still errors and podman does not work.
@boostchicken should we even use this script to install podman or should we just download the latest zip-file from Actions and copy files to specific directories according to zip-file sctructure? What is the correct way to install podman on UDMP 2.5 anyways? Sorry for the offtopic. Tell me if I should make another issue for podman installation.

**Comment by m-lan-at** [comment]
Hmm... I also cannot reach the server "https://unifi.boostchicken.io/" but "ping" works. 🤔 Anyone else? Could I download the file from another server/hoster? Thx a lot :)

**Comment by m-lan-at** [comment]
Results from "https://mxtoolbox.com/domain/" :)

<img width="1487" alt="Bildschirm­foto 2023-03-27 um 16 20 20" src="https://user-images.githubusercontent.com/118959601/227967687-5eefce5f-b7aa-49f5-88bb-63886d6d2d45.png">

**Comment by ezracelli** [comment]
@boostchicken you mentioned in #523 that we could grab the zip file directly from GitHub Actions. Would you (or @m-lan-at / anyone else who knows) mind providing a quick bit of guidance regarding how to package that Actions artifact as `[udmpro/udmse]-podman-install.zip` that has the required `podman-install.zip` nested inside? I don't see any build script that does that packaging in this repo. Thank you!

**Comment by crembz** [comment]
> @boostchicken you mentioned in #523 that we could grab the zip file directly from GitHub Actions. Would you (or @m-lan-at / anyone else who knows) mind providing a quick bit of guidance regarding how to package that Actions artifact as `[udmpro/udmse]-podman-install.zip` that has the required `podman-install.zip` nested inside? I don't see any build script that does that packaging in this repo. Thank you!

I've been struggling with this also! keen to retire my rpi running pihole

**Comment by GY8VSdYYzvL8-K6T** [comment]
Can you upload this file too, please - https://unifi.boostchicken.io/udm-boot-2x_1.0.1_all.deb ?

**Comment by croemmich** [comment]
@GY8VSdYYzvL8-K6T, that one is in the repo: https://github.com/unifi-utilities/unifios-utilities/blob/main/on-boot-script-2.x/packages/udm-boot-2x_1.0.1_all.deb

**Comment by GY8VSdYYzvL8-K6T** [comment]
Thanks! That one actually works!

**Comment by m-lan-at** [comment]
In Fact, that [https://unifi.boostchicken.io](https://unifi.boostchicken.io/udm-boot-2x_1.0.1_all.deb) is still not reachable. I decided to upload the "udmpro-podman-install.zip" on my own server. I grabbed the file from one of my UDM-Pros. The desired file is located in "/data/podman/cache" (last download from boostchicken.io about two/three weeks ago). 

The script "00-podman.sh" in line 34 says "base UDM works fine with udmpro podman version, but has issues with udmse variant". So I can upload the same .zip file for all UDM users except UDM-SE or UDR. 

I have more UDM-SEs and UDRs so I could test podman but I need the desired files. If anyone or @boostchicken have the desired .zip files for UDM-SE and UDR I would upload it to my server for all those who have a problem to download it from 
 "unifi.boostchicken.io".
 
 @ezracelli: I'm sorry but I can't provide a script that does packaging because I haven't dealt with it yet. Also I didn't test to implement the boot-script and podman on UniFi OS 3.x.
 
 @GY8VSdYYzvL8-K6T: I am going to upload the file "udm-boot-2x_1.0.1_all.deb" on my server and I can provide the desired scripts with the new links.

**Comment by zerog2k** [comment]
is it possible to just let github host it as a release (binary package)?

**Comment by m-lan-at** [comment]
@zerog2k : Just use the instructions above for the moment. I think @boostchicken will change links in the future. I could also provide a server for this purpose if needed (cloud provider in austria, europe).

**Comment by JoeOIVOV** [comment]
> URL="https://box.msp-austria.cloud/s/podman/download/${DESIRED_ZIPFILE}"

Just did the update last night to 2.5.17 and ran into a big issue getting podman installed due to site in the script being down. 
I was able to download podman-install.zip from the actions tab on github but it was version 4.4.2 , and giving error:

WARN[0000] Failed to read current user namespace mappings

Once I changed to this URL in install script, it downgraded to 3.4.4 and fixed all the issues,  thank you!

**Comment by davidroman0O** [comment]
Can we re-open this? The website is down again and gives a `A timeout occurred Error code 524` or `failed to resolve /ipns/unifi.boostchicken.io/udmse-podman-install.zip: could not resolve name`  for the podman zip or if directly on the domain domain `failed to resolve /ipns/unifi.boostchicken.io/: could not resolve name`

**Comment by zerog2k** [comment]
Github supports release and posting, and is backed by a global CDN. Why not just let github host the release files?
